#!/bin/bash
# fix_db_names.sh
# Fixes FASTA naming inconsistencies in STRspy2.0-DB generated by BuildDB_From_GeneBank.V1.sh
# Some loci get suffixes like 'mod', 'mod1' that prevent STRspy from finding them.
# Usage: bash fix_db_names.sh <path_to_DB_dir>
# Author: Tamara Frontanilla Recalde (fix) | Original: Kesharwani RK

DB_DIR=${1:-"."}

if [[ ! -d "$DB_DIR" ]]; then
    echo "Error: Directory $DB_DIR not found"
    echo "Usage: bash fix_db_names.sh <path_to_DB_dir>"
    exit 1
fi

echo "Fixing FASTA names in: $DB_DIR"

cd "$DB_DIR"

# Rename mod/mod1 suffixed FASTAs to standard names
for f in *mod1.fa *mod.fa; do
    [[ -f "$f" ]] || continue
    newname=$(echo "$f" | sed 's/mod1\.fa$/.fa/;s/mod\.fa$/.fa/')
    if [[ ! -f "$newname" ]]; then
        cp "$f" "$newname"
        echo "Fixed: $f -> $newname"
    else
        echo "Skipped (already exists): $newname"
    fi
done

echo "Done. All FASTAs renamed."
